server:
  port: 8000
spring:
  application:
    name: ql-im-core
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${remote.server-host}:${remote.mysql-port}/${remote.mysql-database}?serverTimezone=UTC&useSSL=false&characterEncoding=UTF8
    username: ${remote.mysql-username}
    password: ${remote.mysql-password}

  redis:
    host: ${remote.server-host}
    port: ${remote.redis-port}
    password: ${remote.redis-password}
    jedis:
      pool:
        max-active: 100
        max-idle: 100
        max-wait: 1000
        min-idle: 10


# logger 配置
logging:
  config: classpath:logback-spring.xml

mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath*:mapper/*.xml
  global-config:
    db-config:
      update-strategy: NOT_EMPTY

#mybatis:
#  configuration:
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

httpclient:
  maxTotal: 100
  defaultMaxPerRoute: 50
  connectTimeout: 2000
  connectionRequestTimeout: 2000
  socketTimeout: 5000
  staleConnectionCheckEnabled: true

---
spring:
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher

---
swagger:
  scan-packages: com.qianlou.im.service.friendship.controller,com.qianlou.im.service.user.controller,com.qianlou.im.service.group.controller

#允许循环依赖
---
spring:
  main:
    allow-circular-references: true

---
remote:
  server-host: www.qianlou.server.com
  mysql-port: 3306
  mysql-username: db_im
  mysql-password: AbrWz2ndhytcS4TW
  mysql-database: db_im

  redis-port: 6379
  redis-password: 123456
